name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # PYTHON SETUP    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # VULNERABILITY & LINT
    - name: Run Bandit scan
      run: |
        pip install bandit
        bandit -r back-end
        bandit -r front-end

    - name: Run Safety scan
      run: |
        pip install safety
        safety check --file=back-end/requirements.txt --full-report
        safety check --file=front-end/requirements.txt --full-report
        
    - name: Analysing the code with pylint
      run: |
        pip install pylint
        pylint $(git ls-files '*.py')

    # TESTS
    - name: Run back-end tests
      run: |
        pip install pytest
        pip install -r back-end/requirements_test.txt
        pytest back-end/test_app.py

    - name: Run front-end tests
      run: |
        pip install pytest
        pip install -r front-end/requirements_test.txt
        pytest front-end/test_app.py

    # DOCKER
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .
        docker push ghcr.io/${{ github.repository_owner }}/my-app:latest


